version: '3.8'

services:
  backend:
    image: python:3.9
    working_dir: /app
    volumes:
      - ./backend:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    build:
      context: ./backend
      dockerfile: Dockerfile
